name = "MissingLinksFuzzing"
uuid = "adf3615d-95bd-4b61-abc0-04a356a2ab6c"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
MissingLinks = "472ee5c9-fceb-493a-8c64-09683b8345c2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"

[compat]
ArgParse = "1.2.0"
DataFrames = "1.8.1"
Distributions = "0.25.122"
GLMakie = "0.13.8"
GeoDataFrames = "0.3.13"
Graphs = "1.13.1"
LibGEOS = "0.9.6"
LinearAlgebra = "1.12.0"
Logging = "1.11.0"
LoggingExtras = "1.2.0"
Makie = "0.24.8"
MetaGraphsNext = "0.7.5"
MissingLinks = "0.2.0"
Plots = "1.41.3"
ProgressLogging = "0.1.6"
ProgressMeter = "1.11.0"
Random = "1.11.0"
StableRNGs = "1.0.4"
StatsBase = "0.34.9"
Tables = "1.12.1"
TerminalLoggers = "0.1.7"
